### ISSUE TITLE
termux-am reboots phone

### ISSUE THREAD

**Issue by Neo-Oli** [michalbednarski/TermuxAm#2]
I just got handed a weird phone (apparently I now do real life tech support for termux):
The Umidigi s2 lite. (Android 7.0)
On it, using termux-am crashes the rom. So using any api command soft reboots the phone. I "hotfixed" it by replacing the "am" with a link to /system/bin/am (like it was before termux-am). 
Any ideas?

https://transfer.sh/BGrlo/last_kmsg

**Comment by michalbednarski** [comment]
I think that most likely is system_server crash ("soft reboot" as in kernel is not restarted, although your log contains startup of kernel which is against that theory, however it is possible that device decided to do full restart in that case).

termux-am, unlike normal am doesn't do [`sendBroadcast`](https://developer.android.com/reference/android/content/Context#sendBroadcast(android.content.Intent,%20java.lang.String)) directly (or at least equivalent underlying call as we don't have [`Context`](https://developer.android.com/reference/android/content/Context)), because it didn't work without `IApplicationThread` on Oreo so it does [`PendingIntent.getBroadcast()`](https://developer.android.com/reference/android/app/PendingIntent.html#getBroadcast(android.content.Context,%20int,%20android.content.Intent,%20int))`.send()`. (Although PendingIntents are used in system all over place so it would be surprising for them to be broken, however it is possible that system has added required argument that is not provided by termux-am)

Anyway from log I've got I cannot see anything. Probably in this case `logcat` (launched from adb, not Termux app) would be more useful.

**Comment by Neo-Oli** [comment]
I'm going to close this again. I no longer have access to this phone and can therefore not provide more information (the user is now using a different device and doesn't care about this issue anymore).
